version: "3.9"

services:
  attadance_app:
    container_name: attadance_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "5000:5000"
