create table "public"."contacts" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null default 'Example'::character varying,
    "email" character varying not null default 'example@gmail.com'::character varying,
    "no_telp" character varying not null default '08XXXXXXX'::character varying,
    "description" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."contacts" enable row level security;

create table "public"."todo_list" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null default 'example'::character varying,
    "description" character varying not null,
    "completed" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."todo_list" enable row level security;

alter table "public"."students" drop column "nis";

alter table "public"."students" alter column "major" set data type character varying(100) using "major"::character varying(100);

drop type "public"."majors";

CREATE UNIQUE INDEX contacts_pkey ON public.contacts USING btree (id, name, email, no_telp, description, created_at);

CREATE UNIQUE INDEX todo_list_id_key ON public.todo_list USING btree (id);

CREATE UNIQUE INDEX todo_list_pkey ON public.todo_list USING btree (id, name, description, completed, created_at);

alter table "public"."contacts" add constraint "contacts_pkey" PRIMARY KEY using index "contacts_pkey";

alter table "public"."todo_list" add constraint "todo_list_pkey" PRIMARY KEY using index "todo_list_pkey";

alter table "public"."todo_list" add constraint "todo_list_id_key" UNIQUE using index "todo_list_id_key";

grant delete on table "public"."contacts" to "anon";

grant insert on table "public"."contacts" to "anon";

grant references on table "public"."contacts" to "anon";

grant select on table "public"."contacts" to "anon";

grant trigger on table "public"."contacts" to "anon";

grant truncate on table "public"."contacts" to "anon";

grant update on table "public"."contacts" to "anon";

grant delete on table "public"."contacts" to "authenticated";

grant insert on table "public"."contacts" to "authenticated";

grant references on table "public"."contacts" to "authenticated";

grant select on table "public"."contacts" to "authenticated";

grant trigger on table "public"."contacts" to "authenticated";

grant truncate on table "public"."contacts" to "authenticated";

grant update on table "public"."contacts" to "authenticated";

grant delete on table "public"."contacts" to "service_role";

grant insert on table "public"."contacts" to "service_role";

grant references on table "public"."contacts" to "service_role";

grant select on table "public"."contacts" to "service_role";

grant trigger on table "public"."contacts" to "service_role";

grant truncate on table "public"."contacts" to "service_role";

grant update on table "public"."contacts" to "service_role";

grant delete on table "public"."todo_list" to "anon";

grant insert on table "public"."todo_list" to "anon";

grant references on table "public"."todo_list" to "anon";

grant select on table "public"."todo_list" to "anon";

grant trigger on table "public"."todo_list" to "anon";

grant truncate on table "public"."todo_list" to "anon";

grant update on table "public"."todo_list" to "anon";

grant delete on table "public"."todo_list" to "authenticated";

grant insert on table "public"."todo_list" to "authenticated";

grant references on table "public"."todo_list" to "authenticated";

grant select on table "public"."todo_list" to "authenticated";

grant trigger on table "public"."todo_list" to "authenticated";

grant truncate on table "public"."todo_list" to "authenticated";

grant update on table "public"."todo_list" to "authenticated";

grant delete on table "public"."todo_list" to "service_role";

grant insert on table "public"."todo_list" to "service_role";

grant references on table "public"."todo_list" to "service_role";

grant select on table "public"."todo_list" to "service_role";

grant trigger on table "public"."todo_list" to "service_role";

grant truncate on table "public"."todo_list" to "service_role";

grant update on table "public"."todo_list" to "service_role";

create policy "Public profiles are visible to everyone."
on "public"."todo_list"
as permissive
for select
to anon
using (true);



