name: Continuous Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VPS
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check Secrets
        run: |
          echo "APP_ENV=${{ secrets.APP_ENV }}"\
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}"\
          echo "SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}"\
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}"\
          echo "SUPABASE_TABLE=${{ secrets.SUPABASE_TABLE }}"\
          echo "SUPABASE_CONNECTION_STRING=${{ secrets.SUPABASE_CONNECTION_STRING }}"\
          echo "TIME_OUT_CALL_API=${{ secrets.TIME_OUT_CALL_API }}"\
          echo "TIME_INTERVAL_CALL_API=${{ secrets.TIME_INTERVAL_CALL_API }}"\
          echo "UPLOAD_PATH=${{ secrets.UPLOAD_PATH }}"\
          echo "LOG_PATH=${{ secrets.LOG_PATH }}"
