name: Continuous Deploy Workflow

on:
    push:
      branches:
        - master



jobs:
    deploy:
        name: Deploy to VPS
        defaults:
            run:
                shell: bash
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout repository'
            uses: actions/checkout@v2
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.TOKEN_GITHUB}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/tirtahakimpambudhi/flask_system_attandance:latest
              docker push ghcr.io/tirtahakimpambudhi/flask_system_attandance:latest
            # if error build docker buildx build --progress=plain -t ghcr.io/tirtahakimpambudhi/flask_system_attandance:latest .
          - name: Run Container In VPS
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
                script: |
                        if [ "$(docker ps -a -q -f name=flask_system_attandance)" ]; then
                            docker container stop flask_system_attandance &&
                            docker container rm flask_system_attandance
                        fi
                        
                        docker container run -d \
                        --name flask_system_attendance \
                        -e APP_ENV=${{ secrets.APP_ENV }} \
                        -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
                        -e SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }} \
                        -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
                        -e SUPABASE_TABLE=${{ secrets.SUPABASE_TABLE }} \
                        -e SUPABASE_CONNECTION_STRING=${{ secrets.SUPABASE_CONNECTION_STRING }} \
                        -e TIME_OUT_CALL_API=${{ secrets.TIME_OUT_CALL_API }} \
                        -e TIME_INTERVAL_CALL_API=${{ secrets.TIME_INTERVAL_CALL_API }} \
                        -e UPLOAD_PATH=${{ secrets.UPLOAD_PATH }} \
                        -e LOG_PATH=${{ secrets.LOG_PATH }} \
                        -p 5000:5000 \
                        -v app/uploads:${{ secrets.UPLOAD_PATH }} \
                        -v app/logs:${{ secrets.LOG_PATH }} \
                        --cpus 0.5 \  # Batasan CPU di sini
                        ghcr.io/tirtahakimpambudhi/flask_system_attendance:latest
                  
                        # Tunggu sebentar untuk memastikan container dimulai
                        sleep 10s
                    
                        # Hapus gambar yang tidak terpakai
                        docker image prune -f