name: Continuous Integration Workflow

on:
  push:
    branches:
      - master

jobs:
    unit_test:
        name: Testing Python Environtment
        defaults:
            run:
                shell: bash
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: 'Checkout repository'
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10.12'
            - name: 'Setup Environment'
              run: |
                    echo "APP_ENV=${{ secrets.APP_ENV }}" >> $GITHUB_ENV
                    echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
                    echo "SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}" >> $GITHUB_ENV
                    echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
                    echo "SUPABASE_TABLE=${{ secrets.SUPABASE_TABLE }}" >> $GITHUB_ENV
                    echo "SUPABASE_CONNECTION_STRING=${{ secrets.SUPABASE_CONNECTION_STRING }}" >> $GITHUB_ENV
                    echo "TIME_OUT_CALL_API=${{ secrets.TIME_OUT_CALL_API }}" >> $GITHUB_ENV
                    echo "TIME_INTERVAL_CALL_API=${{ secrets.TIME_INTERVAL_CALL_API }}" >> $GITHUB_ENV
                    echo "UPLOAD_PATH=${{ secrets.UPLOAD_PATH }}" >> $GITHUB_ENV
                    echo "LOG_PATH=${{ secrets.LOG_PATH }}" >> $GITHUB_ENV
            - name: 'Check Version'
              run: python3 --version
            - name: 'Setup Dependencies'
              run: sudo apt install make && make linux_venv && make install
            - name: 'Unittest'
              run: make test


            